/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "good_counter.v:1" *)
module good_counter(clk, reset, cnt);
  (* src = "good_counter.v:6" *)
  wire [1:0] _00_;
  (* src = "good_counter.v:6" *)
  wire _01_;
  (* src = "good_counter.v:6" *)
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "good_counter.v:1" *)
  wire _05_;
  (* src = "good_counter.v:1" *)
  wire _06_;
  (* src = "good_counter.v:1" *)
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "good_counter.v:1" *)
  input clk;
  (* src = "good_counter.v:1" *)
  output [1:0] cnt;
  (* src = "good_counter.v:1" *)
  input reset;
  sky130_fd_sc_hd__clkinv_1 _10_ (
    .A(_07_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nor2b_1 _11_ (
    .A(_06_),
    .B_N(_05_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _12_ (
    .A(_05_),
    .B(_06_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _13_ (
    .A(_07_),
    .Y(_03_)
  );
  (* src = "good_counter.v:6" *)
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(cnt[0]),
    .RESET_B(_08_)
  );
  (* src = "good_counter.v:6" *)
  sky130_fd_sc_hd__dfrtp_1 _15_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(cnt[1]),
    .RESET_B(_09_)
  );
  assign _07_ = reset;
  assign _09_ = _04_;
  assign _05_ = cnt[0];
  assign _06_ = cnt[1];
  assign _00_[1] = _02_;
  assign _00_[0] = _01_;
  assign _08_ = _03_;
endmodule
